# قسم إعدادات الخادم
[server]
# تشغيل التطبيق في وضع "headless" (بدون واجهة رسومية للمتصفح المضمن)
# هذا ضروري لبيئات الخادم مثل Streamlit Cloud
headless = true

# تمكين أو تعطيل مشاركة الموارد عبر النطاقات (CORS)
# في معظم الحالات، يمكن تعطيلها لزيادة الأمان ما لم يكن هناك سبب محدد لتمكينها
enableCORS = false

# تحديد المنفذ الذي سيستمع عليه تطبيق Streamlit
# المنفذ 8501 هو المنفذ الافتراضي والموصى به لـ Streamlit
# تغيير هذا يساعد في تجنب تعارض المنافذ مثل "Port 5000 is already in use"
port = 8501
